### ISSUE TITLE
regarding license specification

### ISSUE THREAD

**Issue by koalalovepenguin** [kevzettler/multiplayer-voxel-browser-game-engine#1]
hi! i see your work on HN and I loooooove it

thank you so very much for amazingly fun work

i will try it on my hobby works with some JS doodling

could you please specify the code license?

i am not expert so it may be my lack of knowledge (if i am wrong please forgive me)
but it might be a separate things; the copyright and the open sw code license

thank you so very much again!

**Comment by kevzettler** [comment]
The code licenses is in the README:

This work is licensed under a [Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License](http://creativecommons.org/licenses/by-nc-sa/3.0/).
